### ISSUE TITLE
field set keys method lose quotes of columnKey

### ISSUE THREAD

**Issue by zhyhang** [pilosa/java-pilosa#108]
line 154:

 public PqlBaseQuery set(String rowKey, String columnKey) {
        **return this.index.pqlQuery(String.format("Set(%s,%s='%s')",**
                columnKey, name, rowKey));
    }

**Comment by yuce** [comment]
Thanks for your bug report. The PR that adds `keys` support is at: https://github.com/pilosa/java-pilosa/pull/107
