### ISSUE TITLE
Field options drop string keys setting when field type is time quantum.

### ISSUE THREAD

**Issue by janstenpickle** [pilosa/java-pilosa#151]
As per the title, the java client drops the `keys` option when setting the field type to time quantum, despite the server supporting this setting. I'm currently using version `1.3.0` of the java client.

`FieldOptions.builder().fieldTime(TimeQuantum.YEAR_MONTH_DAY_HOUR).setKeys(true).build().isKeys() == true`

However the output of `toString` is `{"options":{"timeQuantum":"YMDH","type":"time"}}`.

Pilos will accept field options for time quantum with a string field when the following options are posted via curl: `{ "options": { "keys": true, "timeQuantum":"YMDH","type":"time" } }`

**Comment by yuce** [comment]
Thanks for your report. https://github.com/pilosa/java-pilosa/pull/152 fixes this. We are going to release a new version of the library soon.

**Comment by janstenpickle** [comment]
Perfect, thanks very much @yuce

**Comment by yuce** [comment]
@janstenpickle We published version `1.3.1` of the client which contains the fix for this issue.

**Comment by janstenpickle** [comment]
Awesome, thank you very much @yuce
