### ISSUE TITLE
Timestamp not set on column when using bulk importer

### ISSUE THREAD

**Issue by janstenpickle** [pilosa/java-pilosa#163]
Client version: 1.3.3, server version: 1.3.1 and master

As per the title, it seems the timestamp isn't being set when using the bulk importer. I've tried with both epoch millis and epoch seconds, and neither seem to work.

It seems the timestamp field is getting set on the protobufs payload, but it's not getting picked up by the server. If it looks like a problem with the server I can raise there too.

**Comment by yuce** [comment]
Hi @janstenpickle thanks for your issue report. The timestamps should be in nanoseconds. Here's a sample `Record`:
```
Column.create(10, 5, 1542199376000000000L)
```
Note that this library expects the record timestamp for roaring imports to be (wrongly) in seconds. We'll release a new version soon with the correct nanoseconds timestamp resolution. If you were not using roaring imports, nothing needs to change on your side.

You can see the relevant change in this PR: https://github.com/pilosa/java-pilosa/pull/164/files

**Comment by janstenpickle** [comment]
Thanks @yuce, is there somewhere that this is documented? If not I'm happy to add some.

**Comment by yuce** [comment]
That would be great! Import related documentation is in `docs/imports.md`: https://github.com/pilosa/java-pilosa/blob/master/docs/imports.md The timestamps are wrongly in seconds in those docs. Thanks for your contribution!

**Comment by yuce** [comment]
Fixed by https://github.com/pilosa/java-pilosa/pull/166
