### ISSUE TITLE
groupBy does not take a filter option

### ISSUE THREAD

**Issue by timbogatchev** [pilosa/java-pilosa#177]
Per the Pilosa documentation, `GroupBy` can be used with a `filter` option:
https://www.pilosa.com/docs/latest/query-language/#read-operations

> The optional filter argument takes any type of Row query (e.g. Row, Union, Intersect, etc.) which will be intersected with each result prior to returning the count. This is analogous to a WHERE clause applied to a relational GROUP BY query.

Currently this is not supported via the Java client.
https://github.com/pilosa/java-pilosa/blob/master/com.pilosa.client/src/main/java/com/pilosa/client/orm/Index.java#L322

Everything is simply concatenated with a comma, meaning I have to convert the query to a string, add the `filter=(...)` string myself, then cast it back to a `PqlQuery`

**Comment by timbogatchev** [comment]
Should be a very easy fix:

```
    public PqlBaseQuery groupBy(PqlRowsQuery... queries, PqlRowsQuery filter) {
        if (queries.length < 1) {
            throw new IllegalArgumentException("there should be at least one rows query");
        }
        String text;
        if (filter != null) {
            String.format("GroupBy(%s, filter=%s)", joinQueries(queries), filter);
        } else {
            String.format("GroupBy(%s)", joinQueries(queries));
        } 
        return pqlQuery(text, false);
    }
```

**Comment by yuce** [comment]
Hi @timbogatchev, Thanks for submitting this issue. I've pushed a PR  that adds all variants of `GroupBy` at https://github.com/pilosa/java-pilosa/issues/177
