### ISSUE TITLE
Add size method to PqlBatchQuery which returns number of queries in the batch

### ISSUE THREAD

**Issue by yuce** [pilosa/java-pilosa#55]

**Comment by travisturner** [comment]
@yuce can you provide some more details here. what's driving this request?

**Comment by yuce** [comment]
@travisturner  Retrieving the number of queries in a batch is useful, e.g., @linhvo 's batch messages work: https://github.com/pilosa/kafkaconnect/pull/11 This is implemented in https://github.com/pilosa/java-pilosa/pull/56 so we probably should close this ticket.
