### ISSUE TITLE
Result of SetBit or ClearBit query is inaccessible

### ISSUE THREAD

**Issue by brombach** [pilosa/java-pilosa#82]
QueryResult doesn't appear to have any method to access the boolean response from SetBit or ClearBit. I could be missing it, but all the example code also neglects the response.

**Comment by yuce** [comment]
`QueryResult` doesn't return the result from `SetBit` and `ClearBit` currently. How do you intend to use that value?

**Comment by yuce** [comment]
PR https://github.com/pilosa/java-pilosa/pull/86 address this issue. Closing.
